### ISSUE TITLE
pop3 configuration

### ISSUE THREAD

**Issue by EmadAlblueshi** [cdandoy/mail-mock#1]
Hi, 

I'm trying to test reading email inbox pop3 using `javax.mail`

```java
Properties properties = new Properties();
properties.put("mail.pop3.host", "localhost");
properties.put("mail.pop3.port", 110);
```

The README does not show details about the configuration or maybe I miss something ?

**Comment by cdandoy** [comment]
mail-mock uses [GreenMail](https://github.com/greenmail-mail-test/greenmail) as the email server which supports the POP3 protocol.
You will find examples online on how to read emails using POP3.

**Comment by EmadAlblueshi** [comment]
I know how to use it I mean the default user and password for pop3
